version: "3.9"

services:
  server:
    image: spring-server:v1.0
    container_name: server
    build: server/
    restart: always
    ports:
      - "8080:8080"

  client:
    image: react-client:v1.0
    container_name: client
    build: client/
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
