version: "3.8"

services:
  database:
    image: mongo
    container_name: database
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - data:/data/db
    networks:
      - main-network

  server:
    build:
      context: server/
      dockerfile: Dockerfile
    image: spring-server:v1.0
    container_name: server
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - main-network

  client:
    build:
      context: client/
      dockerfile: Dockerfile
    image: react-client:v1.0
    container_name: client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - main-network

volumes:
  data:

networks:
  main-network:
    name: edoc-flow-network